[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "CFA"
version = "0.1.0"
description = "CFA Python package"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

